app = "cartezcash"

[build]
# image = "registry.fly.io/cartezcash:latest"
dockerfile = "./Dockerfile"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "11155111"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0x02370C5B1217b3E80b18132403DE02ee6240e07C"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "5958307"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x9c19314C56238e28107A4122fc536D977a1986C6"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x0cD956B572379DA203D5eEe85f6D17bA3EbF9625"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "3963384"
CARTESI_EPOCH_DURATION = "86400"