app = "cartezcash-fullnode"

[build]
image = "registry.fly.io/cartezcash-fullnode:latest"

[[services]]
  internal_port = 50051
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [services.ports.tls_options]
    alpn = ["h2"]

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
GRPC_SERVER_URL="0.0.0.0:50051"
ROLLUP_HTTP_SERVER_URL="http://cartezcash.internal:10000/graphql"
ETH_CHAIN_ID="11155111"
INPUTBOX_CONTRACT_ADDRESS="0x59b22D57D4f067708AB0c00552767405926dc768"
ETH_RPC_URL="https://eth-sepolia.g.alchemy.com/v2/demo"
DAPP_ADDRESS = "0x589DAc2C23C2bc1b60112eD66049ECba90e7AD3e"
ETH_DEPOSIT_ADDR="0xFfdbe43d4c855BF7e0f105c400A50857f53AB044"
